MyNEAT::Genome
Config MyNEAT.Genome.conf
Referenced by MyNEAT.Genome.Genome, MyNEAT.Genome.MutationAddConnection, MyNEAT.Genome.MutationChangeWeight.
int MyNEAT.Genome.geneIndex
Referenced by MyNEAT.Genome.Genome, MyNEAT.Genome.MutationAddConnection, MyNEAT.Genome.MutationAddNeuron.
List<GConnection> MyNEAT.Genome.connections
Referenced by MyNEAT.Genome.CreateOffSpring, MyNEAT.Genome.Crossover, MyNEAT.Genome.Genome, MyNEAT.Genome.MutationAddConnection, MyNEAT.Genome.MutationAddNeuron, MyNEAT.Genome.MutationChangeWeight, MyNEAT.Genome.MutationRemoveConnection, MyNEAT.Genome.MutationRemoveNeuron, MyNEAT.Genome.ToString.
List<GNeuron> MyNEAT.Genome.neurons
Referenced by MyNEAT.Genome.CreateOffSpring, MyNEAT.Genome.Crossover, MyNEAT.Genome.Genome, MyNEAT.Genome.IsGWithIdExistsInList, MyNEAT.Genome.MutationRemoveNeuron, MyNEAT.Network.Network, MyNEAT.Genome.ToString.
float MyNEAT.Genome.fitness
override string MyNEAT.Genome.ToString()
References MyNEAT.Genome.connections, MyNEAT.Genome.neurons.
int MyNEAT.Genome.GetComplexity()
MyNEAT.Genome.Genome(int inputs, int outputs)
References MyNEAT.Genome.conf, MyNEAT.Genome.connections, MyNEAT.Config.connWeightRange, MyNEAT.Genome.geneIndex, MyNEAT.Genome.neurons.
MyNEAT.Genome.Genome()
References MyNEAT.Genome.conf.
Referenced by MyNEAT.Genome.CreateOffSpring, MyNEAT.Genome.Crossover.
Genome MyNEAT.Genome.CreateOffSpring(Random generator)
Asexual reproduction
References MyNEAT.Genome.connections, MyNEAT.Genome.Genome, MyNEAT.Genome.Mutate, MyNEAT.Genome.neurons.
Genome MyNEAT.Genome.CreateOffSpring(Random generator, Genome otherParent)
Sexual reproduction
generator otherParent
References MyNEAT.Genome.Crossover, MyNEAT.Genome.Mutate.
static Genome MyNEAT.Genome.MutationChangeWeight(Random generator, Genome genome)
References MyNEAT.Genome.conf, MyNEAT.Genome.connections, MyNEAT.Config.connWeightRange, MyNEAT.Config.weightChangeRange.
Referenced by MyNEAT.Genome.Mutate.
static Genome MyNEAT.Genome.MutationAddNeuron(Random generator, Genome genome)
References MyNEAT.Genome.connections, MyNEAT.Genome.geneIndex.
Referenced by MyNEAT.Genome.Mutate.
static Genome MyNEAT.Genome.MutationRemoveNeuron(Random generator, Genome genome)
References MyNEAT.Genome.connections, MyNEAT.Genome.FindAmountOfInAndOutConnectionsForNeuronWithId, MyNEAT.Genome.neurons.
Referenced by MyNEAT.Genome.Mutate.
static Genome MyNEAT.Genome.MutationAddConnection(Random generator, Genome genome)
References MyNEAT.Genome.conf, MyNEAT.Genome.connections, MyNEAT.Config.connWeightRange, MyNEAT.Genome.geneIndex, MyNEAT.Genome.GetListOfInAndOutConnections.
Referenced by MyNEAT.Genome.Mutate.
static Genome MyNEAT.Genome.MutationRemoveConnection(Random generator, Genome genome)
References MyNEAT.Genome.connections.
Referenced by MyNEAT.Genome.Mutate.
static Genome MyNEAT.Genome.Crossover(Random generator, Genome parent1, Genome parent2)
References MyNEAT.Genome.connections, MyNEAT.Genome.Genome, MyNEAT.Genome.IsGWithIdExistsInList, MyNEAT.Genome.neurons.
Referenced by MyNEAT.Genome.CreateOffSpring.
static Genome MyNEAT.Genome.Mutate(Random generator, Genome toMutate)
References MyNEAT.Genome.MutationAddConnection, MyNEAT.Genome.MutationAddNeuron, MyNEAT.Genome.MutationChangeWeight, MyNEAT.Genome.MutationRemoveConnection, MyNEAT.Genome.MutationRemoveNeuron.
Referenced by MyNEAT.Genome.CreateOffSpring.
static bool MyNEAT.Genome.IsGWithIdExistsInList(List< GNeuron > neurons, int id)
References MyNEAT.Genome.neurons.
Referenced by MyNEAT.Genome.Crossover.
static bool MyNEAT.Genome.IsGWithIdExistsInList(List< GConnection > conns, int id)
static int [] MyNEAT.Genome.FindAmountOfInAndOutConnectionsForNeuronWithId(List< GConnection > connectionList, int id)
Referenced by MyNEAT.Genome.MutationRemoveNeuron.
static List<GConnection> [] MyNEAT.Genome.GetListOfInAndOutConnections(List< GConnection > connectionList, int id)
Referenced by MyNEAT.Genome.MutationAddConnection.